### PR TITLE
Support RHEL9

### PR DESCRIPTION
**Pull request by thomas-merz**

### CODE REVIEW

**Comment by thomas-merz** [comment]
I'm not sure about this 'since' - what exactly is this and how relevant is it to be absolutely correct (also for RHEL9)? 🤔

**Comment by laugmanuel** [comment]
The tests should get green as soon as https://github.com/dm-drogeriemarkt/foreman_wreckingball/pull/113 is merged

**Comment by laugmanuel** [comment]
@thomas-merz can you rebase?

**Comment by laugmanuel** [comment]
Thanks @thomas-merz

**Pull request merged**
