### PR TITLE
Support RHEL8 and SLES15

### PR DESCRIPTION
**Pull request by laugmanuel**
This PR adds RHEL8 and SLES15 to the known os identifiers.

### CODE REVIEW

**Review by timogoebel — APPROVED** [review]

**Comment by laugmanuel** [comment]
I'll also add Flatcar to this PR...

**Comment by timogoebel** [comment]
I don't know if that helps, but we can only use identifiers actually known to vsphere. They are not arbitrary if I remember correctly.

**Comment by laugmanuel** [comment]
After https://github.com/dm-drogeriemarkt/foreman_wreckingball/pull/104 is merged, I'll rebase this to get the CI green

**Comment by timogoebel** [comment]
Thanks.

**Pull request merged**
